// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewNeuralNetwork(arg1:number,arg2:Array<number>,arg3:number,arg4:boolean,arg5:Array<any>,arg6:number,arg7:number,arg8:number,arg9:number):Promise<void>;

export function Predict(arg1:Array<string>):Promise<Array<number>>;
