// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewNeuralNetwork(arg1:number,arg2:Array<number>,arg3:number,arg4:boolean):Promise<void>;

export function Train(arg1:Array<any>,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;
